# Generated by Django 2.1.4 on 2019-05-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_process', models.CharField(choices=[('fibonacci', 'fibonacci'), ('wait', 'wait')], max_length=20)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_start', models.DateTimeField()),
                ('date_of_finish', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'pending'), ('S', 'started'), ('F', 'finished')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(default=None, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User'),
        ),
    ]
