# Generated by Django 2.1.2 on 2018-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_request_time_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='time_of_creation',
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
