# Generated by Django 2.1.2 on 2018-12-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20181127_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='pid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='request',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='type_of_process',
            field=models.CharField(choices=[('fibonacci', 'fibonacci'), ('wait', 'wait')], max_length=20),
        ),
    ]
