# Generated by Django 2.1.2 on 2018-12-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20181207_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pid',
            field=models.IntegerField(default=None),
        ),
    ]
