# Generated by Django 2.1.2 on 2018-12-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20181207_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='pid',
            field=models.IntegerField(default=-1),
        ),
    ]
