# Generated by Django 2.1.4 on 2018-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20181207_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='request',
            name='started',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('S', 'started'), ('F', 'finished')], default='X', max_length=1),
            preserve_default=False,
        ),
    ]
