# Generated by Django 2.1.4 on 2019-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190517_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128),
        ),
    ]
