# Generated by Django 2.1.4 on 2019-05-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20190517_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DurationField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
