# Generated by Django 2.1.4 on 2019-05-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20190517_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='pid',
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DurationField(default=None),
        ),
    ]
