# Generated by Django 2.1.4 on 2019-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20190517_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
