# Generated by Django 2.1.4 on 2019-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
