# Generated by Django 2.1.4 on 2019-05-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20190524_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_of_finish',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='date_of_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
