# Generated by Django 2.1.4 on 2019-05-24 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20190524_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_of_finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='date_of_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
